//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 04:34:43 PM MESZ 
//


package at.ahls.web.rest.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for light-data-dto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="light-data-dto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="on" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ct" type="{http://www.ahls.at/AHLS_WebService}colorTemperature" />
 *       &lt;attribute name="bri" type="{http://www.ahls.at/AHLS_WebService}brightness" />
 *       &lt;attribute name="tt" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "light-data-dto")
public class LightDataDto {

    @XmlAttribute
    protected Boolean on;
    @XmlAttribute
    protected Integer ct;
    @XmlAttribute
    protected Integer bri;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedInt")
    protected Long tt;

    /**
     * Gets the value of the on property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOn() {
        return on;
    }

    /**
     * Sets the value of the on property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOn(Boolean value) {
        this.on = value;
    }

    /**
     * Gets the value of the ct property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCt() {
        return ct;
    }

    /**
     * Sets the value of the ct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCt(Integer value) {
        this.ct = value;
    }

    /**
     * Gets the value of the bri property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBri() {
        return bri;
    }

    /**
     * Sets the value of the bri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBri(Integer value) {
        this.bri = value;
    }

    /**
     * Gets the value of the tt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTt() {
        return tt;
    }

    /**
     * Sets the value of the tt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTt(Long value) {
        this.tt = value;
    }

}
