//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 02:31:00 PM MEZ 
//


package at.ahls.web.rest.api.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the at.ahls.web.rest.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Activity_QNAME = new QName("http://www.ahls.at/AHLS_WebService", "activity");
    private final static QName _Activities_QNAME = new QName("http://www.ahls.at/AHLS_WebService", "activities");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: at.ahls.web.rest.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivityType }
     * 
     */
    public ActivityType createActivityType() {
        return new ActivityType();
    }

    /**
     * Create an instance of {@link ActivitiesType }
     * 
     */
    public ActivitiesType createActivitiesType() {
        return new ActivitiesType();
    }

    /**
     * Create an instance of {@link ActivitiesType.Activity }
     * 
     */
    public ActivitiesType.Activity createActivitiesTypeActivity() {
        return new ActivitiesType.Activity();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ahls.at/AHLS_WebService", name = "activity")
    public JAXBElement<ActivityType> createActivity(ActivityType value) {
        return new JAXBElement<ActivityType>(_Activity_QNAME, ActivityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivitiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ahls.at/AHLS_WebService", name = "activities")
    public JAXBElement<ActivitiesType> createActivities(ActivitiesType value) {
        return new JAXBElement<ActivitiesType>(_Activities_QNAME, ActivitiesType.class, null, value);
    }

}
