//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 05:04:34 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ahls.at/AHLS_WebService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package at.ahls.web.rest.api.jaxb;
